# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "pwc" ]
  pull_request:
    branches: [ "pwc" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v -o mkio-ams-migration
